import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// User-provided enriched data (with pos and richer meanings)
const enrichedData = [
  { "word": "abandon", "pos": "Verb", "meaning": "ละทิ้ง, สละ" },
  { "word": "ability", "pos": "Noun", "meaning": "ความสามารถ" },
  { "word": "able", "pos": "Adjective", "meaning": "สามารถ" },
  { "word": "abortion", "pos": "Noun", "meaning": "การทำแท้ง, การแท้งบุตร" },
  { "word": "about", "pos": "Preposition / Adverb", "meaning": "เกี่ยวกับ, ประมาณ" },
  { "word": "above", "pos": "Preposition / Adverb", "meaning": "ข้างบน, เหนือ" },
  { "word": "abroad", "pos": "Adverb", "meaning": "ในต่างประเทศ" },
  { "word": "absence", "pos": "Noun", "meaning": "การขาด, การไม่อยู่" },
  { "word": "absolute", "pos": "Adjective", "meaning": "แน่นอน, สมบูรณ์" },
  { "word": "absolutely", "pos": "Adverb", "meaning": "อย่างแน่นอน" },
  { "word": "absorb", "pos": "Verb", "meaning": "ซึมซับ, ดูดซับ" },
  { "word": "abuse", "pos": "Noun / Verb", "meaning": "การละเมิด, ใช้ในทางที่ผิด" },
  { "word": "academic", "pos": "Adjective / Noun", "meaning": "ทางวิชาการ, นักวิชาการ" },
  { "word": "accept", "pos": "Verb", "meaning": "ยอมรับ" },
  { "word": "access", "pos": "Noun / Verb", "meaning": "ทางเข้า, เข้าถึง" },
  { "word": "accident", "pos": "Noun", "meaning": "อุบัติเหตุ" },
  { "word": "accompany", "pos": "Verb", "meaning": "ร่วมเดินทาง, มากับ" },
  { "word": "accomplish", "pos": "Verb", "meaning": "ทำให้สำเร็จ" },
  { "word": "according (to)", "pos": "Preposition", "meaning": "ตามที่, จาก" },
  { "word": "account", "pos": "Noun / Verb", "meaning": "บัญชี, อธิบาย" },
  { "word": "accurate", "pos": "Adjective", "meaning": "ถูกต้องแม่นยำ" },
  { "word": "accuse", "pos": "Verb", "meaning": "กล่าวหา, กล่าวโทษ" },
  { "word": "achieve", "pos": "Verb", "meaning": "บรรลุ, สำเร็จ" },
  { "word": "achievement", "pos": "Noun", "meaning": "ความสำเร็จ" },
  { "word": "acid", "pos": "Noun / Adjective", "meaning": "กรด, มีฤทธิ์เป็นกรด" },
  { "word": "acknowledge", "pos": "Verb", "meaning": "รับทราบ, ยอมรับ" },
  { "word": "acquire", "pos": "Verb", "meaning": "ได้รับ, ได้มา" },
  { "word": "across", "pos": "Preposition / Adverb", "meaning": "ข้าม, ผ่าน" },
  { "word": "act", "pos": "Verb / Noun", "meaning": "แสดง, การกระทำ" },
  { "word": "action", "pos": "Noun", "meaning": "การกระทำ, แอ็กชัน" },
  { "word": "active", "pos": "Adjective", "meaning": "คล่องแคล่ว, กระตือรือร้น" },
  { "word": "activist", "pos": "Noun", "meaning": "นักกิจกรรม, ผู้เคลื่อนไหว" },
  { "word": "activity", "pos": "Noun", "meaning": "กิจกรรม" },
  { "word": "actor", "pos": "Noun", "meaning": "นักแสดงชาย" },
  { "word": "actress", "pos": "Noun", "meaning": "นักแสดงหญิง" },
  { "word": "actual", "pos": "Adjective", "meaning": "ที่จริง, แท้จริง" },
  { "word": "actually", "pos": "Adverb", "meaning": "จริงๆ แล้ว" },
  { "word": "ad", "pos": "Noun", "meaning": "โฆษณา" },
  { "word": "adapt", "pos": "Verb", "meaning": "ปรับตัว, ดัดแปลง" },
  { "word": "add", "pos": "Verb", "meaning": "เพิ่ม" },
  { "word": "addition", "pos": "Noun", "meaning": "การเพิ่ม, สิ่งที่เพิ่มเข้ามา" },
  { "word": "additional", "pos": "Adjective", "meaning": "ที่เพิ่มเติมขึ้นมา" },
  { "word": "address", "pos": "Noun / Verb", "meaning": "ที่อยู่, จัดการ/รับมือกับปัญหา" },
  { "word": "adequate", "pos": "Adjective", "meaning": "เพียงพอ" },
  { "word": "adjust", "pos": "Verb", "meaning": "ปรับ, ปรับเปลี่ยน" },
  { "word": "adjustment", "pos": "Noun", "meaning": "การปรับตัว, การปรับเปลี่ยน" },
  { "word": "administration", "pos": "Noun", "meaning": "การบริหาร, คณะผู้บริหาร" },
  { "word": "administrator", "pos": "Noun", "meaning": "ผู้บริหาร" },
  { "word": "admire", "pos": "Verb", "meaning": "ชื่นชม" },
  { "word": "admission", "pos": "Noun", "meaning": "การรับเข้า, ค่าธรรมเนียมเข้าชม" },
  { "word": "admit", "pos": "Verb", "meaning": "ยอมรับ, รับเข้าไว้" },
  { "word": "adolescent", "pos": "Noun / Adjective", "meaning": "วัยรุ่น" },
  { "word": "adopt", "pos": "Verb", "meaning": "นำมาใช้, รับเลี้ยงเป็นบุตรบุญธรรม" },
  { "word": "adult", "pos": "Noun / Adjective", "meaning": "ผู้ใหญ่" },
  { "word": "advance", "pos": "Noun / Verb / Adjective", "meaning": "ความก้าวหน้า, ล่วงหน้า" },
  { "word": "advanced", "pos": "Adjective", "meaning": "ก้าวหน้า, ชั้นสูง" },
  { "word": "advantage", "pos": "Noun", "meaning": "ข้อดี, ความได้เปรียบ" },
  { "word": "adventure", "pos": "Noun", "meaning": "การผจญภัย" },
  { "word": "advertising", "pos": "Noun", "meaning": "การโฆษณา" },
  { "word": "advice", "pos": "Noun", "meaning": "คำแนะนำ" },
  { "word": "advise", "pos": "Verb", "meaning": "แนะนำ" },
  { "word": "adviser", "pos": "Noun", "meaning": "ที่ปรึกษา" },
  { "word": "advocate", "pos": "Verb / Noun", "meaning": "สนับสนุน, ผู้สนับสนุน" },
  { "word": "affair", "pos": "Noun", "meaning": "เรื่องราว, เหตุการณ์" },
  { "word": "affect", "pos": "Verb", "meaning": "ส่งผลกระทบต่อ" },
  { "word": "afford", "pos": "Verb", "meaning": "มีเงิน/เวลาเพียงพอที่จะจ่าย" },
  { "word": "afraid", "pos": "Adjective", "meaning": "เกรงกลัว, หวาดกลัว" },
  { "word": "African", "pos": "Adjective / Noun", "meaning": "แอฟริกัน" },
  { "word": "African-American", "pos": "Adjective / Noun", "meaning": "ชาวอเมริกันเชื้อสายแอฟริกัน" },
  { "word": "after", "pos": "Preposition / Conjunction", "meaning": "หลังจาก" },
  { "word": "afternoon", "pos": "Noun", "meaning": "ตอนบ่าย" },
  { "word": "again", "pos": "Adverb", "meaning": "อีกครั้ง" },
  { "word": "against", "pos": "Preposition", "meaning": "ต่อต้าน, พิง" },
  { "word": "age", "pos": "Noun / Verb", "meaning": "อายุ, แก่ตัวลง" },
  { "word": "agency", "pos": "Noun", "meaning": "หน่วยงาน, ตัวแทน" },
  { "word": "agenda", "pos": "Noun", "meaning": "ระเบียบวาระการประชุม" },
  { "word": "agent", "pos": "Noun", "meaning": "ตัวแทน, ตัวการ" },
  { "word": "aggressive", "pos": "Adjective", "meaning": "ก้าวร้าว, รุกราน" },
  { "word": "ago", "pos": "Adverb", "meaning": "มาแล้ว (ใช้บอกเวลาในอดีต)" },
  { "word": "agree", "pos": "Verb", "meaning": "เห็นด้วย, ตกลง" },
  { "word": "agreement", "pos": "Noun", "meaning": "ข้อตกลง, สัญญา" },
  { "word": "agricultural", "pos": "Adjective", "meaning": "ทางการเกษตร" },
  { "word": "ah", "pos": "Interjection", "meaning": "อุทานแสดงความเข้าใจหรือประหลาดใจ" },
  { "word": "ahead", "pos": "Adverb", "meaning": "ข้างหน้า, ล่วงหน้า" },
  { "word": "aid", "pos": "Noun / Verb", "meaning": "ความช่วยเหลือ, ช่วยเหลือ" },
  { "word": "aide", "pos": "Noun", "meaning": "ผู้ช่วย, เสนาธิการ" },
  { "word": "AIDS", "pos": "Noun", "meaning": "โรคเอดส์" },
  { "word": "aim", "pos": "Noun / Verb", "meaning": "จุดมุ่งหมาย, ตั้งเป้า" },
  { "word": "air", "pos": "Noun", "meaning": "อากาศ" },
  { "word": "aircraft", "pos": "Noun", "meaning": "อากาศยาน, เครื่องบิน" },
  { "word": "airline", "pos": "Noun", "meaning": "สายการบิน" },
  { "word": "airport", "pos": "Noun", "meaning": "สนามบิน" },
  { "word": "alarm", "pos": "Noun / Verb", "meaning": "สัญญาณเตือนภัย, ทำให้ตกใจ" },
  { "word": "album", "pos": "Noun", "meaning": "อัลบั้ม" },
  { "word": "alcohol", "pos": "Noun", "meaning": "แอลกอฮอล์" },
  { "word": "alive", "pos": "Adjective", "meaning": "มีชีวิตอยู่" },
  { "word": "all", "pos": "Determiner / Pronoun", "meaning": "ทั้งหมด" },
  { "word": "alliance", "pos": "Noun", "meaning": "พันธมิตร" },
  { "word": "allow", "pos": "Verb", "meaning": "อนุญาต" },
  { "word": "ally", "pos": "Noun / Verb", "meaning": "พันธมิตร, ผูกพันธมิตร" },
  { "word": "almost", "pos": "Adverb", "meaning": "เกือบจะ" },
  { "word": "alone", "pos": "Adjective / Adverb", "meaning": "ตามลำดับ, คนเดียว" },
  { "word": "along", "pos": "Preposition / Adverb", "meaning": "ไปตาม, ร่วมด้วย" },
  { "word": "already", "pos": "Adverb", "meaning": "เรียบร้อยแล้ว" },
  { "word": "also", "pos": "Adverb", "meaning": "อีกด้วย, เช่นกัน" },
  { "word": "alter", "pos": "Verb", "meaning": "ปรับเปลี่ยน, แก้ไข" },
  { "word": "alternative", "pos": "Noun / Adjective", "meaning": "ทางเลือก, ที่เป็นทางเลือก" },
  { "word": "although", "pos": "Conjunction", "meaning": "ถึงแม้ว่า" },
  { "word": "always", "pos": "Adverb", "meaning": "เสมอ, เป็นประจำ" },
  { "word": "AM", "pos": "Abbreviation", "meaning": "ก่อนเที่ยงวัน (A.M.)" },
  { "word": "amazing", "pos": "Adjective", "meaning": "น่าอัศจรรย์" },
  { "word": "American", "pos": "Adjective / Noun", "meaning": "ชาวอเมริกัน" },
  { "word": "among", "pos": "Preposition", "meaning": "ท่ามกลาง, ในหมู่" },
  { "word": "amount", "pos": "Noun", "meaning": "จำนวน" },
  { "word": "analysis", "pos": "Noun", "meaning": "การวิเคราะห์" },
  { "word": "analyst", "pos": "Noun", "meaning": "นักวิเคราะห์" },
  { "word": "analyze", "pos": "Verb", "meaning": "วิเคราะห์" },
  { "word": "ancient", "pos": "Adjective", "meaning": "โบราณ, เก่าแก่" },
  { "word": "and", "pos": "Conjunction", "meaning": "และ" },
  { "word": "anger", "pos": "Noun / Verb", "meaning": "ความโกรธ, ทำให้โกรธ" },
  { "word": "angle", "pos": "Noun", "meaning": "มุม" },
  { "word": "angry", "pos": "Adjective", "meaning": "โกรธ" },
  { "word": "animal", "pos": "Noun", "meaning": "สัตว์" },
  { "word": "anniversary", "pos": "Noun", "meaning": "วันครบรอบ" },
  { "word": "announce", "pos": "Verb", "meaning": "ประกาศ" },
  { "word": "annual", "pos": "Adjective", "meaning": "ประจำปี" },
  { "word": "another", "pos": "Determiner / Pronoun", "meaning": "อีกหนึ่ง, อื่นๆ" },
  { "word": "answer", "pos": "Noun / Verb", "meaning": "คำตอบ, ตอบ" },
  { "word": "anticipate", "pos": "Verb", "meaning": "คาดหมาย, คาดการณ์" },
  { "word": "anxiety", "pos": "Noun", "meaning": "ความวิตกกังวล" },
  { "word": "any", "pos": "Determiner / Pronoun", "meaning": "ใดๆ, บ้าง" },
  { "word": "anybody", "pos": "Pronoun", "meaning": "ใครก็ตาม" },
  { "word": "anymore", "pos": "Adverb", "meaning": "อีกต่อไป" },
  { "word": "anyone", "pos": "Pronoun", "meaning": "ใครก็ตาม" },
  { "word": "anything", "pos": "Pronoun", "meaning": "สิ่งใดก็ตาม" },
  { "word": "anyway", "pos": "Adverb", "meaning": "อย่างไรก็ตาม" },
  { "word": "anywhere", "pos": "Adverb", "meaning": "ที่ไหนก็ตาม" },
  { "word": "apart", "pos": "Adverb", "meaning": "แยกจากกัน" },
  { "word": "apartment", "pos": "Noun", "meaning": "ห้องชุด, อพาร์ตเมนต์" },
  { "word": "apparent", "pos": "Adjective", "meaning": "เห็นได้ชัด" },
  { "word": "apparently", "pos": "Adverb", "meaning": "ตามที่เห็น, ดูเหมือนว่า" },
  { "word": "appeal", "pos": "Noun / Verb", "meaning": "การอุทธรณ์, ดึงดูดความสนใจ" },
  { "word": "appear", "pos": "Verb", "meaning": "ปรากฏ" },
  { "word": "appearance", "pos": "Noun", "meaning": "การปรากฏตัว, รูปลักษณ์ภายนอก" },
  { "word": "apple", "pos": "Noun", "meaning": "แอปเปิ้ล" },
  { "word": "application", "pos": "Noun", "meaning": "ใบสมัคร, แอปพลิเคชัน" },
  { "word": "apply", "pos": "Verb", "meaning": "สมัคร, นำมาใช้" },
  { "word": "appoint", "pos": "Verb", "meaning": "แต่งตั้ง, นัดหมาย" },
  { "word": "appointment", "pos": "Noun", "meaning": "การนัดหมาย" },
  { "word": "appreciate", "pos": "Verb", "meaning": "ซาบซึ้ง, เห็นคุณค่า" },
  { "word": "approach", "pos": "Verb / Noun", "meaning": "เข้าใกล้, วิธีการ" },
  { "word": "appropriate", "pos": "Adjective", "meaning": "เหมาะสม" },
  { "word": "approval", "pos": "Noun", "meaning": "การอนุมัติ, การยินยอม" },
  { "word": "approve", "pos": "Verb", "meaning": "อนุมัติ, เห็นชอบ" },
  { "word": "approximately", "pos": "Adverb", "meaning": "โดยประมาณ" },
  { "word": "Arab", "pos": "Noun / Adjective", "meaning": "ชาวอาหรับ" },
  { "word": "architect", "pos": "Noun", "meaning": "สถาปนิก" },
  { "word": "area", "pos": "Noun", "meaning": "พื้นที่" },
  { "word": "argue", "pos": "Verb", "meaning": "โต้เถียง, ถกเถียง" },
  { "word": "argument", "pos": "Noun", "meaning": "การโต้เถียง, ข้อโต้แย้ง" },
  { "word": "arise", "pos": "Verb", "meaning": "เกิดขึ้น, ลุกขึ้น" },
  { "word": "arm", "pos": "Noun / Verb", "meaning": "แขน, ติดอาวุธ" },
  { "word": "armed", "pos": "Adjective", "meaning": "ติดอาวุธ" },
  { "word": "army", "pos": "Noun", "meaning": "กองทัพบก" },
  { "word": "around", "pos": "Preposition / Adverb", "meaning": "รอบๆ, ประมาณ" },
  { "word": "arrange", "pos": "Verb", "meaning": "จัดเตรียม, จัดเรียง" },
  { "word": "arrangement", "pos": "Noun", "meaning": "การจัดการ, ข้อตกลง" },
  { "word": "arrest", "pos": "Verb / Noun", "meaning": "จับกุม, การจับกุม" },
  { "word": "arrival", "pos": "Noun", "meaning": "การมาถึง" },
  { "word": "arrive", "pos": "Verb", "meaning": "มาถึง" },
  { "word": "art", "pos": "Noun", "meaning": "ศิลปะ" },
  { "word": "article", "pos": "Noun", "meaning": "บทความ, สิ่งของ" },
  { "word": "artist", "pos": "Noun", "meaning": "ศิลปิน" },
  { "word": "artistic", "pos": "Adjective", "meaning": "งดงามทางศิลปะ, มีศิลปะ" },
  { "word": "as", "pos": "Preposition / Conjunction", "meaning": "ในฐานะ, เนื่องจาก, ขณะที่" },
  { "word": "Asian", "pos": "Adjective / Noun", "meaning": "ชาวเอเชีย" },
  { "word": "aside", "pos": "Adverb", "meaning": "ไว้ข้างๆ, กันไว้" },
  { "word": "ask", "pos": "Verb", "meaning": "ถาม, ขอร้อง" },
  { "word": "asleep", "pos": "Adjective", "meaning": "นอนหลับ" },
  { "word": "aspect", "pos": "Noun", "meaning": "แง่มุม, มุมมอง" },
  { "word": "assault", "pos": "Noun / Verb", "meaning": "การโจมตี, ทำร้ายร่างกาย" },
  { "word": "assert", "pos": "Verb", "meaning": "ยืนยัน, ถือสิทธิ์" },
  { "word": "assess", "pos": "Verb", "meaning": "ประเมินผล" },
  { "word": "assessment", "pos": "Noun", "meaning": "การประเมินผล" },
  { "word": "asset", "pos": "Noun", "meaning": "สินทรัพย์, ทรัพย์สิน" },
  { "word": "assign", "pos": "Verb", "meaning": "มอบหมาย, กำหนด" },
  { "word": "assignment", "pos": "Noun", "meaning": "งานที่ได้รับมอบหมาย" },
  { "word": "assist", "pos": "Verb", "meaning": "ช่วยเหลือ" },
  { "word": "assistance", "pos": "Noun", "meaning": "ความช่วยเหลือ" },
  { "word": "assistant", "pos": "Noun", "meaning": "ผู้ช่วย" },
  { "word": "associate", "pos": "Verb / Noun", "meaning": "เชื่อมโยง, เพื่อนร่วมงาน" },
  { "word": "association", "pos": "Noun", "meaning": "สมาคม, การรวมกลุ่ม" },
  { "word": "assume", "pos": "Verb", "meaning": "สมมติ, รับตำแหน่ง" },
  { "word": "assumption", "pos": "Noun", "meaning": "ข้อสมมติฐาน" },
  { "word": "assure", "pos": "Verb", "meaning": "รับประกัน, ยืนยันให้มั่นใจ" },
  { "word": "at", "pos": "Preposition", "meaning": "ที่ (บอกสถานที่/เวลา)" },
  { "word": "athlete", "pos": "Noun", "meaning": "นักกีฬา" },
  { "word": "athletic", "pos": "Adjective", "meaning": "มีแข็งแรงแบบนักกีฬา" },
  { "word": "atmosphere", "pos": "Noun", "meaning": "บรรยากาศ" },
  { "word": "attach", "pos": "Verb", "meaning": "แนบ, ติด" },
  { "word": "attack", "pos": "Verb / Noun", "meaning": "โจมตี, การโจมตี" },
  { "word": "attempt", "pos": "Verb / Noun", "meaning": "พยายาม, ความพยายาม" },
  { "word": "attend", "pos": "Verb", "meaning": "เข้าร่วม, เข้าประชุม" },
  { "word": "attention", "pos": "Noun", "meaning": "ความสนใจ" },
  { "word": "attitude", "pos": "Noun", "meaning": "ทัศนคติ, ท่าทาง" },
  { "word": "attorney", "pos": "Noun", "meaning": "ทนายความ, อัยการ" },
  { "word": "attract", "pos": "Verb", "meaning": "ดึงดูด" },
  { "word": "attractive", "pos": "Adjective", "meaning": "มีเสน่ห์, น่าดึงดูด" },
  { "word": "attribute", "pos": "Noun / Verb", "meaning": "คุณลักษณะ, สภาพว่าเกิดจาก" },
  { "word": "audience", "pos": "Noun", "meaning": "ผู้ชม, ผู้ฟัง" },
  { "word": "author", "pos": "Noun", "meaning": "ผู้เขียน, นักประพันธ์" },
  { "word": "authority", "pos": "Noun", "meaning": "ผู้มีอำนาจ, เจ้าหน้าที่" },
  { "word": "auto", "pos": "Noun", "meaning": "รถยนต์" },
  { "word": "available", "pos": "Adjective", "meaning": "มีอยู่, ว่าง (พร้อมใช้งาน)" },
  { "word": "average", "pos": "Noun / Adjective / Verb", "meaning": "ค่าเฉลี่ย, ปานกลาง" },
  { "word": "avoid", "pos": "Verb", "meaning": "หลีกเลี่ยง" },
  { "word": "award", "pos": "Noun / Verb", "meaning": "รางวัล, มอบรางวัล" },
  { "word": "aware", "pos": "Adjective", "meaning": "รับรู้, ตระหนัก" },
  { "word": "awareness", "pos": "Noun", "meaning": "ความตระหนักรู้" },
  { "word": "away", "pos": "Adverb", "meaning": "ออกไป, ห่างออกไป" },
  { "word": "awful", "pos": "Adjective", "meaning": "แย่มาก, น่ากลัว" },
  { "word": "baby", "pos": "Noun", "meaning": "ทารก, เด็กอ่อน" },
  { "word": "back", "pos": "Noun / Adverb / Verb", "meaning": "หลัง, กลับ, สนับสนุน" },
  { "word": "background", "pos": "Noun", "meaning": "ประวัติความเป็นมา, ฉากหลัง" },
  { "word": "bad", "pos": "Adjective", "meaning": "ไม่ดี, เลวร้าย" },
  { "word": "badly", "pos": "Adverb", "meaning": "อย่างแย่, อย่างรุนแรง" },
  { "word": "bag", "pos": "Noun", "meaning": "กระเป๋า, ถุง" },
  { "word": "bake", "pos": "Verb", "meaning": "อบ (ขนม)" },
  { "word": "balance", "pos": "Noun / Verb", "meaning": "สมดุล, ยอดคงเหลือ" },
  { "word": "ball", "pos": "Noun", "meaning": "ลูกบอล" },
  { "word": "ban", "pos": "Verb / Noun", "meaning": "ห้าม, การสั่งห้าม" },
  { "word": "band", "pos": "Noun", "meaning": "วงดนตรี, สายรัด" },
  { "word": "bank", "pos": "Noun", "meaning": "ธนาคาร, ฝั่งแม่น้ำ" },
  { "word": "bar", "pos": "Noun", "meaning": "บาร์, แท่ง" },
  { "word": "barely", "pos": "Adverb", "meaning": "แทบจะไม่" },
  { "word": "barrel", "pos": "Noun", "meaning": "ถังบาร์เรล" },
  { "word": "barrier", "pos": "Noun", "meaning": "อุปสรรค, สิ่งกีดขวาง" },
  { "word": "base", "pos": "Noun / Verb", "meaning": "ฐาน, ใช้เป็นฐาน" },
  { "word": "baseball", "pos": "Noun", "meaning": "กีฬาเบสบอล" },
  { "word": "basic", "pos": "Adjective", "meaning": "พื้นฐาน" },
  { "word": "basically", "pos": "Adverb", "meaning": "โดยพื้นฐานแล้ว" },
  { "word": "basis", "pos": "Noun", "meaning": "รากฐาน, หลักเกณฑ์" },
  { "word": "basket", "pos": "Noun", "meaning": "ตะกร้า" },
  { "word": "basketball", "pos": "Noun", "meaning": "บาสเกตบอล" },
  { "word": "bathroom", "pos": "Noun", "meaning": "ห้องน้ำ, ห้องอาบน้ำ" },
  { "word": "battery", "pos": "Noun", "meaning": "แบตเตอรี่" },
  { "word": "battle", "pos": "Noun / Verb", "meaning": "การต่อสู้, ต่อสู้" },
  { "word": "be", "pos": "Verb", "meaning": "เป็น, อยู่, คือ" },
  { "word": "beach", "pos": "Noun", "meaning": "ชายหาด" },
  { "word": "bean", "pos": "Noun", "meaning": "ถั่ว" },
  { "word": "bear", "pos": "Noun / Verb", "meaning": "หมี, อดทน, แบกรับ" },
  { "word": "beat", "pos": "Verb / Noun", "meaning": "ตี, ชนะ, จังหวะ" },
  { "word": "beautiful", "pos": "Adjective", "meaning": "สวยงาม" },
  { "word": "beauty", "pos": "Noun", "meaning": "ความงาม" },
  { "word": "because", "pos": "Conjunction", "meaning": "เพราะว่า" },
  { "word": "become", "pos": "Verb", "meaning": "กลายเป็น" },
  { "word": "bed", "pos": "Noun", "meaning": "เตียงนอน" },
  { "word": "bedroom", "pos": "Noun", "meaning": "ห้องนอน" },
  { "word": "beer", "pos": "Noun", "meaning": "เบียร์" },
  { "word": "before", "pos": "Preposition / Conjunction / Adverb", "meaning": "ก่อน" },
  { "word": "begin", "pos": "Verb", "meaning": "เริ่มต้น" },
  { "word": "beginning", "pos": "Noun", "meaning": "จุดเริ่มต้น" },
  { "word": "behavior", "pos": "Noun", "meaning": "พฤติกรรม" },
  { "word": "behind", "pos": "Preposition / Adverb", "meaning": "ข้างหลัง" },
  { "word": "being", "pos": "Noun / Participle", "meaning": "การเป็นอยู่, สิ่งมีชีวิต" },
  { "word": "belief", "pos": "Noun", "meaning": "ความเชื่อ" },
  { "word": "believe", "pos": "Verb", "meaning": "เชื่อ" },
  { "word": "bell", "pos": "Noun", "meaning": "กระดิ่ง, ระฆัง" },
  { "word": "belong", "pos": "Verb", "meaning": "เป็นของ, อยู่ถูกที่" },
  { "word": "below", "pos": "Preposition / Adverb", "meaning": "ด้านล่าง, ต่ำกว่า" },
  { "word": "belt", "pos": "Noun", "meaning": "เข็มขัด" },
  { "word": "bench", "pos": "Noun", "meaning": "ม้านั่ง" },
  { "word": "bend", "pos": "Verb / Noun", "meaning": "โค้ง, งอ" },
  { "word": "beneath", "pos": "Preposition / Adverb", "meaning": "อยู่ใต้, ข้างใต้" },
  { "word": "benefit", "pos": "Noun / Verb", "meaning": "ผลประโยชน์, ได้รับประโยชน์" },
  { "word": "beside", "pos": "Preposition", "meaning": "ข้างๆ" },
  { "word": "besides", "pos": "Preposition / Adverb", "meaning": "นอกเหนือจาก, ยิ่งกว่านั้น" },
  { "word": "best", "pos": "Adjective / Adverb", "meaning": "ดีที่สุด" },
  { "word": "bet", "pos": "Verb / Noun", "meaning": "เดิมพัน, พนัน" },
  { "word": "better", "pos": "Adjective / Adverb", "meaning": "ดีกว่า" },
  { "word": "between", "pos": "Preposition", "meaning": "ระหว่าง" },
  { "word": "beyond", "pos": "Preposition / Adverb", "meaning": "เกินกว่า, พ้น" },
  { "word": "Bible", "pos": "Noun", "meaning": "คัมภีร์ไบเบิล" },
  { "word": "big", "pos": "Adjective", "meaning": "ใหญ่" },
  { "word": "bike", "pos": "Noun", "meaning": "จักรยาน, รถจักรยานยนต์" },
  { "word": "bill", "pos": "Noun / Verb", "meaning": "ใบแจ้งหนี้, ธนบัตร" },
  { "word": "billion", "pos": "Number / Noun", "meaning": "พันล้าน" },
  { "word": "bind", "pos": "Verb", "meaning": "ผูก, พัน, ผูกมัด" },
  { "word": "biological", "pos": "Adjective", "meaning": "ทางชีวภาพ" },
  { "word": "bird", "pos": "Noun", "meaning": "นก" },
  { "word": "birth", "pos": "Noun", "meaning": "การกำเนิด, การเกิด" },
  { "word": "birthday", "pos": "Noun", "meaning": "วันเกิด" },
  { "word": "bit", "pos": "Noun", "meaning": "ชิ้นส่วนเล็กๆ, นิดหน่อย" },
  { "word": "bite", "pos": "Verb / Noun", "meaning": "กัด, การกัด" },
  { "word": "black", "pos": "Adjective / Noun", "meaning": "สีดำ" },
  { "word": "blade", "pos": "Noun", "meaning": "ใบมีด" },
  { "word": "blame", "pos": "Verb / Noun", "meaning": "ตำหนิ, กล่าวโทษ" },
  { "word": "blanket", "pos": "Noun", "meaning": "ผ้าห่ม" },
  { "word": "blind", "pos": "Adjective", "meaning": "ตาบอด" },
  { "word": "block", "pos": "Noun / Verb", "meaning": "ก้อน, ขวาง" },
  { "word": "blood", "pos": "Noun", "meaning": "เลือด" },
  { "word": "blow", "pos": "Verb / Noun", "meaning": "เป่า, ระเบิด, การเป่า" },
  { "word": "blue", "pos": "Adjective / Noun", "meaning": "สีน้ำเงิน, สีฟ้า" },
  { "word": "board", "pos": "Noun / Verb", "meaning": "คณะกรรมการ, แผ่นไม้, ขึ้นรถ/เรือ" },
  { "word": "boat", "pos": "Noun", "meaning": "เรือ" },
  { "word": "body", "pos": "Noun", "meaning": "ร่างกาย, ศพ" },
  { "word": "bomb", "pos": "Noun / Verb", "meaning": "ระเบิด, วางระเบิด" },
  { "word": "bombing", "pos": "Noun", "meaning": "การวางระเบิด" },
  { "word": "bond", "pos": "Noun / Verb", "meaning": "พันธบัตร, สายสัมพันธ์, ผูกพัน" },
  { "word": "bone", "pos": "Noun", "meaning": "กระดูก" },
  { "word": "book", "pos": "Noun / Verb", "meaning": "หนังสือ, จอง" },
  { "word": "boom", "pos": "Noun / Verb", "meaning": "ช่วงรุ่งเรือง, เสียงดังสนั่น" },
  { "word": "boot", "pos": "Noun", "meaning": "รองเท้าบูท" },
  { "word": "border", "pos": "Noun / Verb", "meaning": "ชายแดน, ขอบ" },
  { "word": "born", "pos": "Adjective / Verb (V.3)", "meaning": "เกิด, โดยกำเนิด" },
  { "word": "borrow", "pos": "Verb", "meaning": "ยืม" },
  { "word": "boss", "pos": "Noun", "meaning": "เจ้านาย, นาย" },
  { "word": "both", "pos": "Determiner / Pronoun", "meaning": "ทั้งคู่" },
  { "word": "bother", "pos": "Verb", "meaning": "รบกวน, ตื๊อ" },
  { "word": "bottle", "pos": "Noun", "meaning": "ขวด" },
  { "word": "bottom", "pos": "Noun / Adjective", "meaning": "ด้านล่าง, ก้น" },
  { "word": "boundary", "pos": "Noun", "meaning": "เขตแดน, ขอบเขต" },
  { "word": "bowl", "pos": "Noun", "meaning": "ชาม, ถ้วย" },
  { "word": "box", "pos": "Noun", "meaning": "กล่อง" },
  { "word": "boy", "pos": "Noun", "meaning": "เด็กผู้ชาย" },
  { "word": "boyfriend", "pos": "Noun", "meaning": "แฟน (ผู้ชาย)" },
  { "word": "brain", "pos": "Noun", "meaning": "สมอง" },
  { "word": "branch", "pos": "Noun", "meaning": "สาขา, กิ่งไม้" },
  { "word": "brand", "pos": "Noun", "meaning": "ยี่ห้อ, แบรนด์" },
  { "word": "bread", "pos": "Noun", "meaning": "ขนมปัง" },
  { "word": "break", "pos": "Verb / Noun", "meaning": "แตก/หัก, ช่วงพัก" },
  { "word": "breakfast", "pos": "Noun", "meaning": "อาหารเช้า" },
  { "word": "breast", "pos": "Noun", "meaning": "เต้านม, หน้าอก" },
  { "word": "breath", "pos": "Noun", "meaning": "ลมหายใจ" },
  { "word": "breathe", "pos": "Verb", "meaning": "หายใจ" },
  { "word": "brick", "pos": "Noun", "meaning": "อิฐ" },
  { "word": "bridge", "pos": "Noun", "meaning": "สะพาน" },
  { "word": "brief", "pos": "Adjective", "meaning": "สั้น, กระชับ" },
  { "word": "briefly", "pos": "Adverb", "meaning": "อย่างสั้นๆ, โดยสรุป" },
  { "word": "bright", "pos": "Adjective", "meaning": "สดใส, สว่าง" },
  { "word": "brilliant", "pos": "Adjective", "meaning": "ฉลาดหลักแหลม, สุกใส" },
  { "word": "bring", "pos": "Verb", "meaning": "นำมา, พามา" },
  { "word": "British", "pos": "Adjective / Noun", "meaning": "เกี่ยวกับสหราชอาณาจักร" },
  { "word": "broad", "pos": "Adjective", "meaning": "กว้างขวาง" },
  { "word": "broken", "pos": "Adjective", "meaning": "แตกหัก, เสีย" },
  { "word": "brother", "pos": "Noun", "meaning": "พี่ชาย, น้องชาย" },
  { "word": "brown", "pos": "Adjective / Noun", "meaning": "สีน้ำตาล" },
  { "word": "brush", "pos": "Noun / Verb", "meaning": "แปรง, แปรงฟัน/ผม" },
  { "word": "buck", "pos": "Noun", "meaning": "ดอลลาร์ (คำสแลง), กวางตัวผู้" },
  { "word": "budget", "pos": "Noun / Verb", "meaning": "งบประมาณ" },
  { "word": "build", "pos": "Verb", "meaning": "สร้าง" },
  { "word": "building", "pos": "Noun", "meaning": "อาคาร, ตึก" },
  { "word": "bullet", "pos": "Noun", "meaning": "กระสุนปืน" },
  { "word": "bunch", "pos": "Noun", "meaning": "ช่อ, พวง, กลุ่ม" },
  { "word": "burden", "pos": "Noun / Verb", "meaning": "ภาระ, เป็นภาระ" },
  { "word": "burn", "pos": "Verb / Noun", "meaning": "เผา, ไหม้" },
  { "word": "bury", "pos": "Verb", "meaning": "ฝัง, ฝังศพ" },
  { "word": "bus", "pos": "Noun", "meaning": "รถประจำทาง, รถบัส" },
  { "word": "business", "pos": "Noun", "meaning": "ธุรกิจ" },
  { "word": "busy", "pos": "Adjective", "meaning": "ยุ่ง, ไม่ว่าง" },
  { "word": "but", "pos": "Conjunction / Preposition", "meaning": "แต่, ยกเว้น" },
  { "word": "butter", "pos": "Noun", "meaning": "เนย" },
  { "word": "button", "pos": "Noun", "meaning": "ปุ่ม, กระดุม" },
  { "word": "buy", "pos": "Verb", "meaning": "ซื้อ" },
  { "word": "buyer", "pos": "Noun", "meaning": "ผู้ซื้อ" },
  { "word": "by", "pos": "Preposition / Adverb", "meaning": "โดย, ข้างๆ" },
  { "word": "cabin", "pos": "Noun", "meaning": "กระท่อม, ห้องโดยสาร" },
  { "word": "cabinet", "pos": "Noun", "meaning": "ตู้, คณะรัฐมนตรี" },
  { "word": "cable", "pos": "Noun", "meaning": "สายเคเบิล" },
  { "word": "cake", "pos": "Noun", "meaning": "เค้ก" },
  { "word": "calculate", "pos": "Verb", "meaning": "คำนวณ" },
  { "word": "call", "pos": "Verb / Noun", "meaning": "เรียก, โทรศัพท์" },
  { "word": "camera", "pos": "Noun", "meaning": "กล้องถ่ายรูป" },
  { "word": "camp", "pos": "Noun / Verb", "meaning": "ค่าย, ค้างแรม" },
  { "word": "campaign", "pos": "Noun / Verb", "meaning": "การรณรงค์" },
  { "word": "campus", "pos": "Noun", "meaning": "วิทยาเขต" },
  { "word": "can", "pos": "Modal Verb / Noun", "meaning": "สามารถ, กระป๋อง" },
  { "word": "Canadian", "pos": "Adjective / Noun", "meaning": "ชาวแคนาดา" },
  { "word": "cancer", "pos": "Noun", "meaning": "โรคมะเร็ง" },
  { "word": "candidate", "pos": "Noun", "meaning": "ผู้สมัคร" },
  { "word": "cap", "pos": "Noun", "meaning": "หมวกแก๊ป, ฝาปิด" },
  { "word": "capability", "pos": "Noun", "meaning": "ความสามารถ" },
  { "word": "capable", "pos": "Adjective", "meaning": "ที่มีความสามารถ" },
  { "word": "capacity", "pos": "Noun", "meaning": "ความจุ, ความสามารถ" },
  { "word": "capital", "pos": "Noun / Adjective", "meaning": "เมืองหลวง, เงินทุน" },
  { "word": "captain", "pos": "Noun", "meaning": "กัปตัน, กัปตันทีม" },
  { "word": "capture", "pos": "Verb / Noun", "meaning": "จับกุม, บันทึกภาพ" },
  { "word": "car", "pos": "Noun", "meaning": "รถยนต์" },
  { "word": "carbon", "pos": "Noun", "meaning": "คาร์บอน" },
  { "word": "card", "pos": "Noun", "meaning": "บัตร, การ์ด" },
  { "word": "care", "pos": "Noun / Verb", "meaning": "การดูแล, ห่วงใย" },
  { "word": "career", "pos": "Noun", "meaning": "อาชีพ" },
  { "word": "careful", "pos": "Adjective", "meaning": "ระมัดระวัง" },
  { "word": "carefully", "pos": "Adverb", "meaning": "อย่างระมัดระวัง" },
  { "word": "carrier", "pos": "Noun", "meaning": "ผู้ขนส่ง, ผู้ให้บริการเครือข่าย" },
  { "word": "carry", "pos": "Verb", "meaning": "ถือ, พกพา" },
  { "word": "case", "pos": "Noun", "meaning": "กรณี, คดี" },
  { "word": "cash", "pos": "Noun", "meaning": "เงินสด" },
  { "word": "cast", "pos": "Verb / Noun", "meaning": "หล่อ, ขว้าง, นักแสดง" },
  { "word": "cat", "pos": "Noun", "meaning": "แมว" },
  { "word": "catch", "pos": "Verb", "meaning": "จับ, คว้า" },
  { "word": "category", "pos": "Noun", "meaning": "หมวดหมู่, ประเภท" },
  { "word": "Catholic", "pos": "Adjective / Noun", "meaning": "คาทอลิก" },
  { "word": "cause", "pos": "Noun / Verb", "meaning": "สาเหตุ, ทำให้เกิด" },
  { "word": "ceiling", "pos": "Noun", "meaning": "เพดาน" },
  { "word": "celebrate", "pos": "Verb", "meaning": "เฉลิมฉลอง" },
  { "word": "celebration", "pos": "Noun", "meaning": "งานเฉลิมฉลอง" },
  { "word": "celebrity", "pos": "Noun", "meaning": "คนดัง, มีชื่อเสียง" },
  { "word": "cell", "pos": "Noun", "meaning": "เซลล์, ห้องขัง" },
  { "word": "center", "pos": "Noun / Verb", "meaning": "ศูนย์กลาง" },
  { "word": "central", "pos": "Adjective", "meaning": "ศูนย์กลาง, สำคัญ" },
  { "word": "century", "pos": "Noun", "meaning": "ศตวรรษ (100 ปี)" },
  { "word": "CEO", "pos": "Noun", "meaning": "ประธานบริหาร (CEO)" },
  { "word": "ceremony", "pos": "Noun", "meaning": "พิธีการ" },
  { "word": "certain", "pos": "Adjective", "meaning": "แน่นอน, บางอย่าง" },
  { "word": "certainly", "pos": "Adverb", "meaning": "อย่างแน่นอน" },
  { "word": "chain", "pos": "Noun / Verb", "meaning": "โซ่, ห่วงโซ่" },
  { "word": "chair", "pos": "Noun", "meaning": "เก้าอี้" },
  { "word": "chairman", "pos": "Noun", "meaning": "ประธาน" },
  { "word": "challenge", "pos": "Noun / Verb", "meaning": "ความท้าทาย, ท้าทาย" },
  { "word": "chamber", "pos": "Noun", "meaning": "ห้องสภา, ห้องโถง" },
  { "word": "champion", "pos": "Noun", "meaning": "แชมป์, ผู้ชนะเลิศ" },
  { "word": "championship", "pos": "Noun", "meaning": "การแข่งขันชิงแชมป์" },
  { "word": "chance", "pos": "Noun", "meaning": "โอกาส" },
  { "word": "change", "pos": "Verb / Noun", "meaning": "เปลี่ยนแปลง, เงินทอน" },
  { "word": "changing", "pos": "Adjective", "meaning": "ที่กำลังเปลี่ยนแปลง" },
  { "word": "channel", "pos": "Noun", "meaning": "ช่องสัญญาณ, ช่องทาง" },
  { "word": "chapter", "pos": "Noun", "meaning": "บท (หนังสือ)" },
  { "word": "character", "pos": "Noun", "meaning": "ตัวละคร, บุคลิกลักษณะ" },
  { "word": "characteristic", "pos": "Noun / Adjective", "meaning": "ลักษณะเฉพาะ" },
  { "word": "characterize", "pos": "Verb", "meaning": "อธิบายลักษณะ" },
  { "word": "charge", "pos": "Verb / Noun", "meaning": "คิดราคา, ชาร์จไฟ, ข้อหา" },
  { "word": "charity", "pos": "Noun", "meaning": "การกุศล" },
  { "word": "chart", "pos": "Noun / Verb", "meaning": "แผนภูมิ, ตาราง" },
  { "word": "chase", "pos": "Verb / Noun", "meaning": "ไล่ตาม, การไล่ล่า" },
  { "word": "cheap", "pos": "Adjective", "meaning": "ราคาถูก" },
  { "word": "check", "pos": "Verb / Noun", "meaning": "ตรวจสอบ, ใบเสร็จ" },
  { "word": "cheek", "pos": "Noun", "meaning": "แก้ม" },
  { "word": "cheese", "pos": "Noun", "meaning": "ชีส" },
  { "word": "chef", "pos": "Noun", "meaning": "พ่อครัว, เชฟ" },
  { "word": "chemical", "pos": "Adjective / Noun", "meaning": "สารเคมี, ทางเคมี" },
  { "word": "chest", "pos": "Noun", "meaning": "หน้าอก, หีบ" },
  { "word": "chicken", "pos": "Noun", "meaning": "ไก่" },
  { "word": "chief", "pos": "Noun / Adjective", "meaning": "หัวหน้า, ที่สำคัญที่สุด" },
  { "word": "child", "pos": "Noun", "meaning": "เด็ก" },
  { "word": "childhood", "pos": "Noun", "meaning": "วัยเด็ก" },
  { "word": "Chinese", "pos": "Adjective / Noun", "meaning": "ชาวจีน, ภาษาจีน" },
  { "word": "chip", "pos": "Noun", "meaning": "ชิป, มันฝรั่งทอด, เศษไม้" },
  { "word": "chocolate", "pos": "Noun", "meaning": "ช็อกโกแลต" },
  { "word": "choice", "pos": "Noun", "meaning": "ตัวเลือก, ทางเลือก" },
  { "word": "cholesterol", "pos": "Noun", "meaning": "คอเลสเตอรอล" },
  { "word": "choose", "pos": "Verb", "meaning": "เลือก" },
  { "word": "Christian", "pos": "Adjective / Noun", "meaning": "ชาวคริสต์" },
  { "word": "Christmas", "pos": "Noun", "meaning": "คริสต์มาส" },
  { "word": "church", "pos": "Noun", "meaning": "โบสถ์" },
  { "word": "cigarette", "pos": "Noun", "meaning": "บุหรี่" },
  { "word": "circle", "pos": "Noun / Verb", "meaning": "วงกลม, หมุนรอบ" },
  { "word": "circumstance", "pos": "Noun", "meaning": "สถานการณ์, แวดล้อม" },
  { "word": "cite", "pos": "Verb", "meaning": "อ้างอิง" },
  { "word": "citizen", "pos": "Noun", "meaning": "พลเมือง" },
  { "word": "city", "pos": "Noun", "meaning": "เมืองใหญ่" },
  { "word": "civil", "pos": "Adjective", "meaning": "เกี่ยวกับพลเรือน, ประชาชน" },
  { "word": "civilian", "pos": "Noun / Adjective", "meaning": "พลเรือน (ไม่ใช่ทหาร)" },
  { "word": "claim", "pos": "Verb / Noun", "meaning": "เรียกร้อง, การอ้างสิทธิ์" },
  { "word": "class", "pos": "Noun", "meaning": "ชั้นเรียน, ชนชั้น" },
  { "word": "classic", "pos": "Adjective / Noun", "meaning": "คลาสสิก, ดั้งเดิม" },
  { "word": "classroom", "pos": "Noun", "meaning": "ห้องเรียน" },
  { "word": "clean", "pos": "Adjective / Verb", "meaning": "สะอาด, ทำความสะอาด" },
  { "word": "clear", "pos": "Adjective / Verb", "meaning": "ชัดเจน, เคลียร์/ทำให้โล่ง" },
  { "word": "clearly", "pos": "Adverb", "meaning": "อย่างชัดเจน" },
  { "word": "client", "pos": "Noun", "meaning": "ลูกค้า" },
  { "word": "climate", "pos": "Noun", "meaning": "สภาพภูมิอากาศ" },
  { "word": "climb", "pos": "Verb", "meaning": "ปีน, ไต่" },
  { "word": "clinic", "pos": "Noun", "meaning": "คลินิก" },
  { "word": "clinical", "pos": "Adjective", "meaning": "ทางคลินิก" },
  { "word": "clock", "pos": "Noun", "meaning": "นาฬิกา" },
  { "word": "close", "pos": "Verb / Adjective", "meaning": "ปิด, ใกล้ชิด" },
  { "word": "closely", "pos": "Adverb", "meaning": "อย่างใกล้ชิด" },
  { "word": "closer", "pos": "Adjective / Adverb", "meaning": "ใกล้เข้ามาอีก" },
  { "word": "clothes", "pos": "Noun", "meaning": "เสื้อผ้า" },
  { "word": "clothing", "pos": "Noun", "meaning": "เสื้อผ้าเครื่องแต่งกาย" },
  { "word": "cloud", "pos": "Noun", "meaning": "ก้อนเมฆ" },
  { "word": "club", "pos": "Noun", "meaning": "สโมสร, คลับ" },
  { "word": "clue", "pos": "Noun", "meaning": "เบาะแส, เงื่อนงำ" },
  { "word": "cluster", "pos": "Noun / Verb", "meaning": "กลุ่ม, รวมเป็นกลุ่ม" },
  { "word": "coach", "pos": "Noun / Verb", "meaning": "โค้ช, ฝึกสอน" },
  { "word": "coal", "pos": "Noun", "meaning": "ถ่านหิน" },
  { "word": "coalition", "pos": "Noun", "meaning": "รัฐบาลผสม, การรวมกลุ่ม" },
  { "word": "coast", "pos": "Noun", "meaning": "ชายฝั่ง" },
  { "word": "coat", "pos": "Noun", "meaning": "เสื้อโค้ท, เสื้อคลุม" },
  { "word": "code", "pos": "Noun / Verb", "meaning": "รหัส, การเขียนโค้ด" },
  { "word": "coffee", "pos": "Noun", "meaning": "กาแฟ" },
  { "word": "cognitive", "pos": "Adjective", "meaning": "เกี่ยวกับการรับรู้/ความคิด" },
  { "word": "cold", "pos": "Adjective / Noun", "meaning": "หนาว, ไข้หวัด" },
  { "word": "collapse", "pos": "Verb / Noun", "meaning": "พังทลาย, ล่มสลาย" },
  { "word": "colleague", "pos": "Noun", "meaning": "เพื่อนร่วมงาน" },
  { "word": "collect", "pos": "Verb", "meaning": "สะสม, รวบรวม" },
  { "word": "collection", "pos": "Noun", "meaning": "ของสะสม, ชุดรวบรวม" },
  { "word": "collective", "pos": "Adjective", "meaning": "ร่วมกัน, โดยรวม" },
  { "word": "college", "pos": "Noun", "meaning": "วิทยาลัย" },
  { "word": "colonial", "pos": "Adjective", "meaning": "เกี่ยวกับอาณานิคม" },
  { "word": "color", "pos": "Noun / Verb", "meaning": "สี, ระบายสี" },
  { "word": "column", "pos": "Noun", "meaning": "คอลัมน์, เสา" },
  { "word": "combination", "pos": "Noun", "meaning": "การรวมกัน, การผสมผสาน" },
  { "word": "combine", "pos": "Verb", "meaning": "รวมเข้าด้วยกัน" },
  { "word": "come", "pos": "Verb", "meaning": "มา" },
  { "word": "comedy", "pos": "Noun", "meaning": "ตลก, ความขบขัน" },
  { "word": "comfort", "pos": "Noun / Verb", "meaning": "ความสะดวกสบาย, ปลอบโยน" },
  { "word": "comfortable", "pos": "Adjective", "meaning": "สบาย" },
  { "word": "command", "pos": "Noun / Verb", "meaning": "คำสั่ง, สั่งการ" },
  { "word": "commander", "pos": "Noun", "meaning": "ผู้บังคับบัญชา" },
  { "word": "comment", "pos": "Noun / Verb", "meaning": "ความคิดเห็น, แสดงความคิดเห็น" },
  { "word": "commercial", "pos": "Adjective / Noun", "meaning": "เชิงพาณิชย์, โฆษณาทางทีวี" },
  { "word": "commission", "pos": "Noun", "meaning": "คณะกรรมาธิการ, ค่านายหน้า" },
  { "word": "commit", "pos": "Verb", "meaning": "ทำความผิด, ผูกมัด" },
  { "word": "commitment", "pos": "Noun", "meaning": "พันธะสัญญา, ความมุ่งมั่น" },
  { "word": "committee", "pos": "Noun", "meaning": "คณะกรรมการ" },
  { "word": "common", "pos": "Adjective", "meaning": "ทั่วไป, ธรรมดา" },
];

// Build a lookup from the enriched data (key by lowercased word)
const enrichedMap = new Map();
for (const item of enrichedData) {
  // Handle special cases like "according (to)" -> match to "according"
  const key = item.word.toLowerCase().replace(/\s*\(.*?\)\s*/g, "").trim();
  enrichedMap.set(key, item);
}

// Read existing words.json
const existingPath = resolve(__dirname, "../src/data/words.json");
const existingWords = JSON.parse(readFileSync(existingPath, "utf-8"));

// Merge: for each existing word, try to find enriched data
const updatedWords = existingWords.map((word) => {
  const key = word.word.toLowerCase().trim();
  const enriched = enrichedMap.get(key);
  
  if (enriched) {
    return {
      word: word.word,
      pos: enriched.pos,
      meaning: enriched.meaning, // Use richer meaning from enriched data
    };
  }
  
  // No match found, keep original but add empty pos
  return {
    word: word.word,
    pos: "",
    meaning: word.meaning,
  };
});

// Count stats
const matchedCount = updatedWords.filter((w) => w.pos !== "").length;
const unmatchedCount = updatedWords.filter((w) => w.pos === "").length;

console.log(`Total words: ${updatedWords.length}`);
console.log(`Matched with pos: ${matchedCount}`);
console.log(`Unmatched (no pos): ${unmatchedCount}`);

// Write back
writeFileSync(existingPath, JSON.stringify(updatedWords, null, 2) + "\n", "utf-8");
console.log("Updated words.json successfully!");
